services:
  - type: web
    name: image-enhancer
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: PORT
        value: 8001
    healthCheckPath: /health
